#!/usr/bin/env bash
#
# Generates a .env.local-style file from Bitwarden Secrets Manager.
#
# Usage:
#   write_env_local_from_bws.sh <project_name> [output_path]
#
# Required environment variables:
#   BWS_ACCESS_TOKEN
#
# Dependencies: bash 4+, jq, Bitwarden Secrets Manager CLI (bws)
#
set -euo pipefail

PROJECT_NAME="${1:-}"
OUTPUT_PATH="${2:-.env.local}"

if [[ -z "$PROJECT_NAME" ]]; then
  echo "[ERROR] Usage: write_env_local_from_bws.sh <project_name> [output_path]" >&2
  exit 1
fi

: "${BWS_ACCESS_TOKEN:?BWS_ACCESS_TOKEN env var is required}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export BWS_PROJECT_NAME="$PROJECT_NAME"

SECRETS_JSON="$(${SCRIPT_DIR}/fetch_bws_secret.sh)"
if [[ -z "$SECRETS_JSON" || "$SECRETS_JSON" == "null" ]]; then
  echo "[ERROR] No secrets returned from Bitwarden project '$PROJECT_NAME'." >&2
  exit 1
fi

TMP_FILE="$(mktemp "${OUTPUT_PATH}.tmp.XXXXXX")"
{
  echo "# Generated by devops-toolkit"
  echo "# Source: Bitwarden project ${PROJECT_NAME}"
  echo "$SECRETS_JSON" | jq -r 'to_entries | map(select(.value != null)) | sort_by(.key) | map("\(.key)=\(.value|tostring|@json)") | .[]'
} > "$TMP_FILE"

if [[ -f "$OUTPUT_PATH" ]]; then
  if cmp -s "$TMP_FILE" "$OUTPUT_PATH"; then
    rm -f "$TMP_FILE"
    echo "[INFO] ${OUTPUT_PATH} is up to date"
    exit 0
  fi
fi

chmod 600 "$TMP_FILE"
mv "$TMP_FILE" "$OUTPUT_PATH"

echo "[INFO] Updated ${OUTPUT_PATH}"
